selector_cookies = "/html/body/div[4]/div/div/button[1]"
selector_Info_button="section > main > div > div > div > div > button"
selector_nom_hashtag="section > main > header > div > div > div > h1"
selector_nbpost="section > main > header > div > div > div > span > span"
selector_firstpost="section > main > article > div > div > div > div:nth-child(1) > div:nth-child(1) > a"
selector_nextpost="/html/body/div[6]/div[1]/div/div/a"
selector_nextpost2="/html/body/div[6]/div[1]/div/div/a[2]"
selector_datepub="div.k_Q0X.I0_K8.NnvRN > a > time"
selector_likes="section > div > div > a > span"
selector_description="article > div > div > div > div> div> ul > div > li > div > div > div > span"
"""
for instasemaine test
"""
selector_nomhash="/html/body/div[1]/section/nav/div[2]/div/div/div[2]/div[3]/div/div[2]/div/div[1]/a/div/div[2]/div[2]/div/span/span"
selector_nbrposts="/html/body/div[1]/section/nav/div[2]/div/div/div[2]/div[3]/div/div[2]/div/div[1]/a/div/div[2]/div[1]/div/div"